from get_clubs_id import get_clubs_id
from get_players_achievements import get_players_achievements
from insert_player_achievement import insert_player_achievement

clubs_id = get_clubs_id('BRA1')
players_achievements = get_players_achievements(clubs_id)
insert_player_achievement(players_achievements)