def translate_position(position):
  translations = {
    "Goalkeeper": "Goleiro",
    "Sweeper": "Líbero",
    "Centre-Back": "Zagueiro",
    "Left-Back": "Lateral Esquerdo",
    "Right-Back": "Lateral Direito",
    "Defensive Midfield": "Volante",
    "Central Midfield": "Meio Campo",
    "Right Midfield": "Meia Direita",
    "Left Midfield": "Meia Esquerda",
    "Attacking Midfield": "Meia Ofensivo",
    "Left Winger": "Ponta Esquerda",
    "Right Winger": "Ponta Direita",
    "Second Striker": "Segundo Atacante",
    "Centre-Forward": "Centroavante"
  }
  return translations.get(position, position)

def translate_country(country):
  translations = {
    "Haiti": "Haiti",
    "Afghanistan": "Afeganistão",
    "Albania": "Albânia",
    "Algeria": "Argélia",
    "American Samoa": "Samoa Americana",
    "American Virgin Islands": "Ilhas Virgens Americanas",
    "Andorra": "Andorra",
    "Angola": "Angola",
    "Anguilla": "Anguila",
    "Antigua and Barbuda": "Antígua e Barbuda",
    "Argentina": "Argentina",
    "Armenia": "Armênia",
    "Aruba": "Aruba",
    "Australia": "Austrália",
    "Austria": "Áustria",
    "Azerbaijan": "Azerbaijão",
    "Bahamas": "Bahamas",
    "Bahrain": "Bahrein",
    "Bangladesh": "Bangladesh",
    "Barbados": "Barbados",
    "Belarus": "Bielorrússia",
    "Belgium": "Bélgica",
    "Belize": "Belize",
    "Benin": "Benim",
    "Bermuda": "Bermudas",
    "Bhutan": "Butão",
    "Bolivia": "Bolívia",
    "Bonaire": "Bonaire",
    "Bosnia-Herzegovina": "Bósnia-Herzegovina",
    "Botswana": "Botsuana",
    "Brazil": "Brasil",
    "British India": "Índia Britânica",
    "British Virgin Islands": "Ilhas Virgens Britânicas",
    "Brunei Darussalam": "Brunei",
    "Bulgaria": "Bulgária",
    "Burkina Faso": "Burkina Faso",
    "Burundi": "Burundi",
    "Cambodia": "Camboja",
    "Cameroon": "Camarões",
    "Canada": "Canadá",
    "Cape Verde": "Cabo Verde",
    "Cayman Islands": "Ilhas Cayman",
    "Central African Republic": "República Centro-Africana",
    "Chad": "Chade",
    "Chile": "Chile",
    "China": "China",
    "Chinese Taipei": "Taipei Chinês",
    "Christmas Island": "Ilha Christmas",
    "Colombia": "Colômbia",
    "Comoros": "Comores",
    "Congo": "Congo",
    "Cookinseln": "Ilhas Cook",
    "Costa Rica": "Costa Rica",
    "Cote d'Ivoire": "Costa do Marfim",
    "Crimea": "Crimeia",
    "Croatia": "Croácia",
    "CSSR": "Checoslováquia",
    "Cuba": "Cuba",
    "Curacao": "Curaçao",
    "Cyprus": "Chipre",
    "Czech Republic": "República Tcheca",
    "Denmark": "Dinamarca",
    "Djibouti": "Djibouti",
    "Dominica": "Dominica",
    "Dominican Republic": "República Dominicana",
    "DR Congo": "República Democrática do Congo",
    "East Germany (GDR)": "Alemanha Oriental (RDA)",
    "Ecuador": "Equador",
    "Egypt": "Egito",
    "El Salvador": "El Salvador",
    "England": "Inglaterra",
    "Equatorial Guinea": "Guiné Equatorial",
    "Eritrea": "Eritreia",
    "Estonia": "Estônia",
    "Eswatini": "Essuatíni",
    "Ethiopia": "Etiópia",
    "Falkland Islands": "Ilhas Malvinas",
    "Faroe Islands": "Ilhas Faroé",
    "Federated States of Micronesia": "Estados Federados da Micronésia",
    "Fiji": "Fiji",
    "Finland": "Finlândia",
    "France": "França",
    "French Guiana": "Guiana Francesa",
    "Gabon": "Gabão",
    "Georgia": "Geórgia",
    "Germany": "Alemanha",
    "Ghana": "Gana",
    "Gibraltar": "Gibraltar",
    "Greece": "Grécia",
    "Greenland": "Groenlândia",
    "Grenada": "Granada",
    "Guadeloupe": "Guadalupe",
    "Guam": "Guam",
    "Guatemala": "Guatemala",
    "Guernsey": "Guernsey",
    "Guinea": "Guiné",
    "Guinea-Bissau": "Guiné-Bissau",
    "Guyana": "Guiana",
    "Honduras": "Honduras",
    "Hongkong": "Hong Kong",
    "Hungary": "Hungria",
    "Iceland": "Islândia",
    "India": "Índia",
    "Indonesia": "Indonésia",
    "Iran": "Irã",
    "Iraq": "Iraque",
    "Ireland": "Irlanda",
    "Isle of Man": "Ilha de Man",
    "Israel": "Israel",
    "Italy": "Itália",
    "Jamaica": "Jamaica",
    "Japan": "Japão",
    "Jersey": "Jersey",
    "Jordan": "Jordânia",
    "Kazakhstan": "Cazaquistão",
    "Kenya": "Quênia",
    "Kiribati": "Kiribati",
    "Korea, North": "Coreia do Norte",
    "Korea, South": "Coreia do Sul",
    "Kosovo": "Kosovo",
    "Kuwait": "Kuwait",
    "Kyrgyzstan": "Quirguistão",
    "Laos": "Laos",
    "Latvia": "Letônia",
    "Lebanon": "Líbano",
    "Lesotho": "Lesoto",
    "Liberia": "Libéria",
    "Libya": "Líbia",
    "Liechtenstein": "Liechtenstein",
    "Lithuania": "Lituânia",
    "Luxembourg": "Luxemburgo",
    "Macao": "Macau",
    "Macedonia": "Macedônia",
    "Madagascar": "Madagáscar",
    "Malawi": "Malaui",
    "Malaysia": "Malásia",
    "Maldives": "Maldivas",
    "Mali": "Mali",
    "Malta": "Malta",
    "Marshall Islands": "Ilhas Marshall",
    "Martinique": "Martinica",
    "Mauritania": "Mauritânia",
    "Mauritius": "Maurício",
    "Mayotte": "Mayotte",
    "Mexico": "México",
    "Moldova": "Moldávia",
    "Monaco": "Mônaco",
    "Mongolia": "Mongólia",
    "Montenegro": "Montenegro",
    "Montserrat": "Montserrat",
    "Morocco": "Marrocos",
    "Mozambique": "Moçambique",
    "Myanmar": "Mianmar",
    "Namibia": "Namíbia",
    "Nauru": "Nauru",
    "Nepal": "Nepal",
    "Netherlands": "Países Baixos",
    "Netherlands Antilles": "Antilhas Holandesas",
    "New Zealand": "Nova Zelândia",
    "Nicaragua": "Nicarágua",
    "Niger": "Níger",
    "Nigeria": "Nigéria",
    "North Macedonia": "Macedônia do Norte",
    "Norway": "Noruega",
    "Oman": "Omã",
    "Pakistan": "Paquistão",
    "Palestine": "Palestina",
    "Panama": "Panamá",
    "Papua New Guinea": "Papua-Nova Guiné",
    "Paraguay": "Paraguai",
    "Peru": "Peru",
    "Philippines": "Filipinas",
    "Poland": "Polônia",
    "Portugal": "Portugal",
    "Puerto Rico": "Porto Rico",
    "Qatar": "Catar",
    "Romania": "Romênia",
    "Russia": "Rússia",
    "Rwanda": "Ruanda",
    "San Marino": "San Marino",
    "Saudi Arabia": "Arábia Saudita",
    "Scotland": "Escócia",
    "Senegal": "Senegal",
    "Serbia": "Sérvia",
    "Singapore": "Singapura",
    "Slovakia": "Eslováquia",
    "Slovenia": "Eslovênia",
    "South Africa": "África do Sul",
    "Spain": "Espanha",
    "Sri Lanka": "Sri Lanka",
    "Sudan": "Sudão",
    "Suriname": "Suriname",
    "Sweden": "Suécia",
    "Switzerland": "Suíça",
    "Syria": "Síria",
    "Thailand": "Tailândia",
    "Turkey": "Turquia",
    "Ukraine": "Ucrânia",
    "United Arab Emirates": "Emirados Árabes Unidos",
    "United States": "Estados Unidos",
    "Uruguay": "Uruguai",
    "Uzbekistan": "Uzbequistão",
    "Vanuatu": "Vanuatu",
    "Vatican": "Vaticano",
    "Venezuela": "Venezuela",
    "Vietnam": "Vietnã",
    "Zambia": "Zâmbia",
    "Zimbabwe": "Zimbábue"
  }
  return translations.get(country, country)

def translate_foot(foot):
  translation = {
    "right": "Direito",
    "left": "Esquerdo",
    "both": "Ambos",
  }
  return translation.get(foot, foot)

def translate_market_value(marketValue):
  if not marketValue:
    return None
  try:
    if marketValue[-1] == 'k':
      return float(marketValue[1:-1]) * 1000
    elif marketValue[-1] == 'm':
        return float(marketValue[1:-1]) * 1000000
    else:
      return float(marketValue[1:])
  except ValueError:
    print(f"Erro ao converter o valor de mercado: {marketValue}")
    return None