CREATE TABLE players(
	player_id INTEGER PRIMARY KEY,
	player_position VARCHAR(50),
	shortName VARCHAR(100),
	fullName VARCHAR(200),
	club INTEGER,
	joinedClub DATE,
	contractExpires DATE,
	dateOfBirth DATE,
	countryOfBirth VARCHAR(100),
	cityOfBirth VARCHAR(100),
	age INT,
	height NUMERIC,
	marketValue MONEY,
	imageURL TEXT,
	foot VARCHAR(10),
	shirtNumber INTEGER,
	agent VARCHAR(100),
	outfitter VARCHAR(50),
	socialMedia VARCHAR(200)
);